export const LOAD_GAMES_LIST_START = "games/LOAD_GAMES_LIST_START";
export const LOAD_GAMES_LIST_SUCCESS = "games/LOAD_GAMES_LIST_SUCCESS";
export const LOAD_GAMES_LIST_ERROR = "games/LOAD_GAMES_LIST_ERROR";
