export const LOAD_GAMES_START = "games/LOAD_GAMES_START";
export const LOAD_GAMES_LIST_SUCCESS = "games/LOAD_GAMES_LIST_SUCCESS";
export const LOAD_GAME_SINGLE_SUCCESS = "games/LOAD_GAME_SINGLE_SUCCESS";
export const LOAD_GAMES_ERROR = "games/LOAD_GAMES_ERROR";
