export const LOAD_PLATFORMS_START = "platforms/LOAD_PLATFORMS_START";
export const LOAD_PLATFORMS_LIST_SUCCESS =
  "platforms/LOAD_PLATFORMS_LIST_SUCCESS";
export const LOAD_PLATFORMS_SINGLE_SUCCESS =
  "platforms/LOAD_PLATFORMS_SINGLE_SUCCESS";
export const LOAD_PLATFORMS_ERROR = "platforms/LOAD_PLATFORMS_ERROR";
