export const orderingList = [
  { name: "Relevance", value: "" },
  { name: "Name", value: "name" },
  { name: "Release date", value: "released" },
  { name: "Metacritic", value: "-metacritic" },
];

export const platformsList = [
  { name: "Any platforms", value: "" },
  { name: "PC", value: 4 },
  { name: "Web", value: 171 },
  { name: "macOS", value: 5 },
  { name: "iOS", value: 3 },
  { name: "Linux", value: 6 },
  { name: "Android", value: 21 },
  { name: "PlayStation 4", value: 18 },
  { name: "Xbox One", value: 1 },
  { name: "Nintendo Switch", value: 7 },
  { name: "PlayStation 3", value: 16 },
  { name: "Xbox 360", value: 14 },
  { name: "Wii", value: 11 },
  { name: "Nintendo DS", value: 9 },
  { name: "Commodore / Amiga", value: 166 },
  { name: "PS Vita", value: 19 },
  { name: "PlayStation 2", value: 15 },
  { name: "Nintendo 3DS", value: 8 },
  { name: "PSP", value: 17 },
  { name: "PlayStation", value: 27 },
  { name: "Wii U", value: 10 },
  { name: "Game Boy Advance", value: 24 },
  { name: "NES", value: 49 },
  { name: "SNES", value: 79 },
  { name: "Genesis", value: 167 },
  { name: "Atari ST", value: 34 },
  { name: "Xbox", value: 80 },
  { name: "Classic Macintosh", value: 55 },
  { name: "GameCube", value: 105 },
  { name: "Game Boy", value: 26 },
  { name: "PlayStation 5", value: 187 },
  { name: "Apple II", value: 41 },
  { name: "Game Boy Color", value: 43 },
  { name: "Nintendo 64", value: 83 },
  { name: "Xbox Series S/X", value: 186 },
  { name: "Dreamcast", value: 106 },
  { name: "SEGA Saturn", value: 107 },
  { name: "Atari 8-bit", value: 25 },
  { name: "Atari 2600", value: 23 },
  { name: "SEGA Master System", value: 74 },
  { name: "Game Gear", value: 77 },
  { name: "SEGA CD", value: 119 },
  { name: "Neo Geo", value: 12 },
  { name: "3DO", value: 111 },
  { name: "Atari 5200", value: 31 },
  { name: "Atari 7800", value: 28 },
  { name: "Atari Lynx", value: 46 },
  { name: "SEGA 32X", value: 117 },
  { name: "Jaguar", value: 112 },
  { name: "Nintendo DSi", value: 13 },
  { name: "Atari Flashback", value: 22 },
  { name: "Atari XEGS", value: 50 },
];

export const genresList = [
  { name: "Any genres", value: "" },
  { name: "Action", value: 4 },
  { name: "Adventure", value: 3 },
  { name: "Arcade", value: 11 },
  { name: "Board Games", value: 28 },
  { name: "Card", value: 17 },
  { name: "Casual", value: 40 },
  { name: "Educational", value: 34 },
  { name: "Family", value: 19 },
  { name: "Fighting", value: 6 },
  { name: "Indie", value: 51 },
  { name: "Massively Multiplayer", value: 59 },
  { name: "Platformer", value: 83 },
  { name: "Puzzle", value: 7 },
  { name: "Racing", value: 1 },
  { name: "RPG", value: 5 },
  { name: "Shooter", value: 2 },
  { name: "Simulation", value: 14 },
  { name: "Sports", value: 15 },
  { name: "Strategy", value: 10 },
];
